version: '3'

services:
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=playlistor
      - POSTGRES_USER=playlistor
      - POSTGRES_DB=playlistor
    ports:
      - "5432:5432"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    command: ./manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - db
  celery:
    build: .
    command: ./manage.py runworker
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
volumes:
  postgres_data: