version: '3'

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  web:
    build: .
    command: bash -c "python ./manage.py migrate --noinput && python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
  celery:
    build: .
    command: bash -c "python ./manage.py runworker"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
