# Generated by Django 2.2.16 on 2020-12-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0008_auto_20201022_1655")]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="applemusic_url",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="playlist", name="spotify_url", field=models.URLField(null=True)
        ),
    ]
