# Generated by Django 2.2.19 on 2021-04-01 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0009_auto_20201226_1334")]

    operations = [
        migrations.AddField(
            model_name="playlist", name="artwork_url", field=models.URLField(null=True)
        )
    ]
