# Generated by Django 3.2 on 2021-05-05 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0010_playlist_artwork_url")]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
            ],
        )
    ]
