# Generated by Django 3.2 on 2021-05-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("main", "0011_subscriber")]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="creator",
            field=models.CharField(max_length=255, null=True),
        )
    ]
